_commit: 0.6.1
_src_path: gh:selrahcd/copier-php-kata
include_docker: true
include_sample_test: true
include_tcr_script: true
kata_name: MarsRover
tell_about_test_run_logger: true
test_run_logger: true
